--SERIAL_NUMBER_OF_THE_INVOICES онъпдйнбши мнлеп яверю тюйрспш
--щрн рн врн ббндхр онкэгнбюрекэ

--1
SELECT DATE_OF_INVOICING FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю';
--2
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю');
--3
SELECT ADDRESS FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю');
--4
SELECT INN_OF_INDIV FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю');
--5
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC||' '||ADDRESS FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT SHIP_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю');
--6
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC||' '||ADDRESS FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT CONS_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю');
--7
SELECT NUMBER_OF_PAYMENT_DOCUMENT FROM XMLD_UTD_PAYMENT_DOCUMENTS WHERE HOLDER_ID=
    (SELECT UTD_ID FROM XMLD_UTD_HEADERS WHERE XMLD_UTD_HEADERS.SERIAL_NUMBER_OF_THE_INVOICES='Ббнд');
--8
SELECT DATE_OF_CREATING_PAYMENT_DOC FROM XMLD_UTD_PAYMENT_DOCUMENTS WHERE HOLDER_ID=
    (SELECT UTD_ID FROM XMLD_UTD_HEADERS WHERE XMLD_UTD_HEADERS.SERIAL_NUMBER_OF_THE_INVOICES='Ббнд');
--9
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.BUYER_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю');
--10
SELECT ADDRESS FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.BUYER_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю');
--11
SELECT INN_OF_INDIV FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT BUYER_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю');
--12
SELECT NAME_OF_VALUTA||' '||CURS_OF_VALUTA FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю';
--13



--14 I 16 I 18 ме асдел онйю онрнл

--15
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE NAME_OF_ORG =(SELECT NAME_OF_ORG FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю')) AND PARTICIPANT_TYPE='псйнбнпхрекэ хкх нрберярбеммне кхжн';
--17
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE NAME_OF_ORG =(SELECT NAME_OF_ORG FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю')) AND PARTICIPANT_TYPE='цкюбмши асуцюкреп хкх нрберярбеммне кхжн';
--19
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE NAME_OF_ORG =(SELECT NAME_OF_ORG FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю')) AND PARTICIPANT_TYPE='хмдхбхдсюкэмши опедопхмхлюрекэ хкх нрберярбеммне кхжн';
--20
SELECT REQ_OF_THE_CERTIF FROM XMLD_PARTICIPANTS WHERE NAME_OF_ORG =(SELECT NAME_OF_ORG FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'гмювемхе ббндю')) AND PARTICIPANT_TYPE='хмдхбхдсюкэмши опедопхмхлюрекэ хкх нрберярбеммне кхжн';