--SERIAL_NUMBER_OF_THE_INVOICES ПОЯРДКОВЫЙ НОМЕР СЧЕТА ФАКТУРЫ
--ЭТО ТО ЧТО ВВОДИТ ПОЛЬЗОВАТЕЛЬ

--1
SELECT DATE_OF_INVOICING FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА';
--2
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА');
--3
SELECT ADDRESS FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА');
--4
SELECT INN_OF_INDIV FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА');
--5
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC||' '||ADDRESS FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT SHIP_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА');
--6
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC||' '||ADDRESS FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT CONS_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА');
--7
SELECT NUMBER_OF_PAYMENT_DOCUMENT FROM XMLD_UTD_PAYMENT_DOCUMENTS WHERE HOLDER_ID=
    (SELECT UTD_ID FROM XMLD_UTD_HEADERS WHERE XMLD_UTD_HEADERS.SERIAL_NUMBER_OF_THE_INVOICES='вВОД');
--8
SELECT DATE_OF_CREATING_PAYMENT_DOC FROM XMLD_UTD_PAYMENT_DOCUMENTS WHERE HOLDER_ID=
    (SELECT UTD_ID FROM XMLD_UTD_HEADERS WHERE XMLD_UTD_HEADERS.SERIAL_NUMBER_OF_THE_INVOICES='вВОД');
--9
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.BUYER_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА');
--10
SELECT ADDRESS FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.BUYER_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА');
--11
SELECT INN_OF_INDIV FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT BUYER_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА');
--12
SELECT NAME_OF_VALUTA||' '||CURS_OF_VALUTA FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА';
--13
--названия столбцов
select 'Название торава',
        'Код товара',
        'Код единицы измерения',
        'Условное обозначение единицы измерения',
        'Количество',
        'Цена товара',
        'Стоимость товаров, без налога - всего',
        'Сумма акциза',
        'Налоговая ставка',
        'Сумма налога, предъявляемая покупателю',
        'Стоимость товаров, с налогом - всего',
        'Цифровой код страны происхождения товара',
        'Краткое наименование страны происхождения товара' from dual;
--заполнение данными
select NAME_OF_PRODUCT as "Название торава",
        CODE_OF_Product as "Код товара",
        UNIT_CODE as "Код единицы измерения",
        UNIT_NAME as "Условное обозначение единицы измерения",
        QUANTITY as "Количество",
        PRICE_OF_UNIT as "Цена товара",
        SUM_OF_PRODUCT_WITHOUT_TAX as "Стоимость товаров, без налога - всего",
        SUM_OF_EXCISE as "Сумма акциза",
        TAX_RATE as "Налоговая ставка",
        SUM_OF_TAX as "Сумма налога, предъявляемая покупателю",
        SUM_OF_PRODUCT_WITH_TAX as "Стоимость товаров, с налогом - всего",
        COUNTRY_CODE_OF_PRODUCT as "Цифровой код страны происхождения товара",
        BRIEF_NAME_OF_COUNTRY_OF_PROD as "Краткое наименование страны происхождения товара" 
        from XMLD_UTD_LINES 
            where UTD_ID = (select UTD_ID from XMLD_UTD_HEADERS where  SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА' );

--14 I 16 I 18 НЕ БУДЕМ ПОКА ПОТОМ

--15
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE NAME_OF_ORG =(SELECT NAME_OF_ORG FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА')) AND PARTICIPANT_TYPE='РУКОВОРИТЕЛЬ ИЛИ ОТВЕТСТВЕННОЕ ЛИЦО';
--17
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE NAME_OF_ORG =(SELECT NAME_OF_ORG FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА')) AND PARTICIPANT_TYPE='ГЛАВНЫЙ БУХГАЛТЕР ИЛИ ОТВЕТСТВЕННОЕ ЛИЦО';
--19
SELECT SECOND_NAME||' '||FIRST_NAME||' '||PATRONYMIC FROM XMLD_PARTICIPANTS WHERE NAME_OF_ORG =(SELECT NAME_OF_ORG FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА')) AND PARTICIPANT_TYPE='ИНДИВИДУАЛЬНЫЙ ПРЕДПРИНИМАТЕЛЬ ИЛИ ОТВЕТСТВЕННОЕ ЛИЦО';
--20
SELECT REQ_OF_THE_CERTIF FROM XMLD_PARTICIPANTS WHERE NAME_OF_ORG =(SELECT NAME_OF_ORG FROM XMLD_PARTICIPANTS WHERE PARTICIPANT_ID = 
    (SELECT XMLD_UTD_HEADERS.VENDOR_PARTICIPANT_ID FROM XMLD_UTD_HEADERS WHERE SERIAL_NUMBER_OF_THE_INVOICES = 'ЗНАЧЕНИЕ ВВОДА')) AND PARTICIPANT_TYPE='ИНДИВИДУАЛЬНЫЙ ПРЕДПРИНИМАТЕЛЬ ИЛИ ОТВЕТСТВЕННОЕ ЛИЦО';